### PR TITLE
Add scrolling to my_courses if it is too long

### PR DESCRIPTION
**Pull request by weiqingtoh**
scrolling-all-courses

Solves Coursemology/coursemology2#2441

### CODE REVIEW

**Comment by allenwq** [comment]
Actually what are we trying to fix ? I feel it's inconvenient that user needs to scroll in a short list to find the course or click "All Courses"

**Comment by fonglh** [comment]
On a short screen, the user cannot access the "All Courses" item if the dropdown list is longer than the screen.

**Comment by weiqingtoh** [comment]
The other more correct way is to set the height to say 75% of the viewport width. I realise you can set that using CSS [from this link](https://tutorialzine.com/2015/05/simplify-your-stylesheets-with-the-magical-css-viewport-units). What do you guys think?

**Comment by fonglh** [comment]
Relative to viewport is better.

**Comment by allenwq** [comment]
👍 Yah that sounds better, users will benefit from big screens.

**Comment by weiqingtoh** [comment]
Updated. This should look more palatable. 

updated-scroll-menu

**Review by fonglh — APPROVED** [review]

**Pull request merged**
