### PR TITLE
Fix footer in theme

### PR DESCRIPTION
**Pull request by nicholette**
screenshot 2017-02-07 18 12 23

### CODE REVIEW

**Comment by nicholette** [comment]
Fixes #11

**Comment by weiqingtoh** [comment]
Shall we hide part of the footer for smaller screens? Don't think it's useful to see so much. Was thinking we can hide the `Coursemology.org All Rights Reserved` part.

**Comment by nicholette** [comment]
I think it's alright to leave it there since people usually don't see it anyway. Hmm yanjie is not in this repo, would be good to ask him about it.

**Comment by weiqingtoh** [comment]
Let's merge this first to fix the issue, we can rethink how to do the entire footer properly later on.

**Comment by allenwq** [comment]
@nicholette seems the new footer has some issues with the React pages, can you help fix as well ?
image

**Comment by fonglh** [comment]
I'll roll this back first, it's causing usability issues as the `Submit` button can't be clicked.

**Pull request merged**
