### PR TITLE
Update About page

### PR DESCRIPTION
**Pull request by allenwq**
- Translates the about page of v1 from ERB to SLIM
- Update the images
- Team section still pending to update

### CODE REVIEW

**Comment by allenwq** [comment]
=_= Also got hound here

**Comment by allenwq** [comment]
Fixed most of the conflicts, the depth one probably won't fix...

**Comment by weiqingtoh** [comment]
Maybe I merge this first and work on it later on to clean up? I think we can use more of the bootstrap classes without having to override some of the settings (which I did a lot of in v1) >_<

**Comment by allenwq** [comment]
OK 👍 

I also want to verify if the files are in the correct place and work on production, works in my local.

**Pull request merged**
